// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvA150zWwjm8HWot4yMqjm4KluK3SVCko',
    appId: '1:275462815074:web:772a0942037b1a0df5003b',
    messagingSenderId: '275462815074',
    projectId: 'chat-app-crashlyticss',
    authDomain: 'chat-app-crashlyticss.firebaseapp.com',
    storageBucket: 'chat-app-crashlyticss.appspot.com',
    measurementId: 'G-QFCGPTXZP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVeKkm7_zvdhn5zViP4iv_ZjstxAicazA',
    appId: '1:275462815074:android:1c8f2af4dc032b3cf5003b',
    messagingSenderId: '275462815074',
    projectId: 'chat-app-crashlyticss',
    storageBucket: 'chat-app-crashlyticss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0_k6FaYbBcsPrLoYrDUbwsa9vgvbklrk',
    appId: '1:275462815074:ios:306bd90c76151433f5003b',
    messagingSenderId: '275462815074',
    projectId: 'chat-app-crashlyticss',
    storageBucket: 'chat-app-crashlyticss.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0_k6FaYbBcsPrLoYrDUbwsa9vgvbklrk',
    appId: '1:275462815074:ios:306bd90c76151433f5003b',
    messagingSenderId: '275462815074',
    projectId: 'chat-app-crashlyticss',
    storageBucket: 'chat-app-crashlyticss.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvA150zWwjm8HWot4yMqjm4KluK3SVCko',
    appId: '1:275462815074:web:aed8c935f7e8b7e2f5003b',
    messagingSenderId: '275462815074',
    projectId: 'chat-app-crashlyticss',
    authDomain: 'chat-app-crashlyticss.firebaseapp.com',
    storageBucket: 'chat-app-crashlyticss.appspot.com',
    measurementId: 'G-CFYPD4T7Z3',
  );
}
